name: test cucumbers
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Configuration de Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Spécifier la version de Java que vous souhaitez utiliser, par exemple '11'
        distribution: jdk # Ajoutez cette ligne pour spécifier la distribution Java
 
    - name: Construction du projet
      run: mvn clean install  # Adapter la commande de construction selon votre projet

    - name: Exécution des tests
      run: mvn test  # Adapter la commande d'exécution des tests selon votre projet

    - name: Archiver le rapport d'exécution
      uses: actions/upload-artifact@v2
      with:
        name: Rapport d'exécution
        path: target/cucumber-reports
